first_name = input("Enter your first name: ")
food = input("Enter your favorite food: ")
email = input("Enter your email address: ")
age = input("Enter your age: ")
quantity = input("Enter your favorite number: ")
num_of_students = input("Enter the number of students in your class: ")
gpa = input("Enter your GPA: ")
is_student = input("Are you a student? (yes/no): ")
print(f"Hello, {first_name}! It's great to know that you love {food}.")
print(f"We have recorded your email as {email}. You are {age} years old and your favorite number is {quantity}.")
print(f"There are {num_of_students} students in your class. Welcome aboard!")
print(f"Your GPA of {gpa} is impressive. Keep up the good work!")
print(f"Student status: {'Yes' if is_student.lower() == 'yes' else 'No'}.")
# This program collects user information and displays a summary message.
